result_1 = {1: {'average_payoff_neighbours_strat0': 16.0,
     'average_payoff_neighbours_strat1': 40.0,
     'new_strategy': 1,
     'supervisor_strategy': 1,
     'total_payoff_supervisor': 40},
 2: {'average_payoff_neighbours_strat0': 16.0,
     'average_payoff_neighbours_strat1': 40.0,
     'new_strategy': 1,
     'supervisor_strategy': 0,
     'total_payoff_supervisor': 16},
 3: {'average_payoff_neighbours_strat0': 16.0,
     'average_payoff_neighbours_strat1': 40.0,
     'new_strategy': 1,
     'supervisor_strategy': 1,
     'total_payoff_supervisor': 40},
 4: {'average_payoff_neighbours_strat0': 16.0,
     'average_payoff_neighbours_strat1': 40.0,
     'new_strategy': 1,
     'supervisor_strategy': 0,
     'total_payoff_supervisor': 16}}



data = {1: {'average_payoff_neighbours_strat1': -6.5,
     'average_payoff_neighbours_strat2': -1.0,
     'average_payoff_neighbours_strat3': -2.0,
     'match_id': [(1, 0)],
     'match_strategy': 3,
     'new_strategy': 2,
     'participant_location': (0, 0),
     'participant_payoff': -8,
     'strategy': 3,
     'supervisor_number': 1,
     'supervisor_payoff': 16,
     'supervisor_state': 1},
 2: {'average_payoff_neighbours_strat1': -6.5,
     'average_payoff_neighbours_strat2': -3.5,
     'average_payoff_neighbours_strat3': -6.0,
     'match_id': [(1, 1)],
     'match_strategy': 2,
     'new_strategy': 2,
     'participant_location': (0, 1),
     'participant_payoff': -1,
     'strategy': 2,
     'supervisor_number': 1,
     'supervisor_payoff': 4,
     'supervisor_state': 1},
 3: {'average_payoff_neighbours_strat1': 0,
     'average_payoff_neighbours_strat2': -1.8333333333333333,
     'average_payoff_neighbours_strat3': -2.0,
     'match_id': [(0, 0)],
     'match_strategy': 3,
     'new_strategy': 1,
     'participant_location': (1, 0),
     'participant_payoff': -8,
     'strategy': 3,
     'supervisor_number': 1,
     'supervisor_payoff': 16,
     'supervisor_state': 1},
 4: {'average_payoff_neighbours_strat1': 0,
     'average_payoff_neighbours_strat2': -3.5,
     'average_payoff_neighbours_strat3': -5.0,
     'match_id': [(0, 1)],
     'match_strategy': 2,
     'new_strategy': 3,
     'participant_location': (1, 1),
     'participant_payoff': -1,
     'strategy': 2,
     'supervisor_number': 1,
     'supervisor_payoff': 4,
     'supervisor_state': 1},
 5: {'average_payoff_neighbours_strat1': -4.0,
     'average_payoff_neighbours_strat2': -1.0,
     'average_payoff_neighbours_strat3': -5.0,
     'match_id': [(0, 1)],
     'match_strategy': 3,
     'new_strategy': 3,
     'participant_location': (0, 0),
     'participant_payoff': -6.5,
     'strategy': 1,
     'supervisor_number': 2,
     'supervisor_payoff': 4,
     'supervisor_state': 0},
 6: {'average_payoff_neighbours_strat1': -5.25,
     'average_payoff_neighbours_strat2': -1.8333333333333333,
     'average_payoff_neighbours_strat3': -8.0,
     'match_id': [(0, 0)],
     'match_strategy': 1,
     'new_strategy': 1,
     'participant_location': (0, 1),
     'participant_payoff': -2,
     'strategy': 3,
     'supervisor_number': 2,
     'supervisor_payoff': 4,
     'supervisor_state': 0},
 7: {'average_payoff_neighbours_strat1': 0,
     'average_payoff_neighbours_strat2': -1.0,
     'average_payoff_neighbours_strat3': -5.6,
     'match_id': [(1, 1)],
     'match_strategy': 3,
     'new_strategy': 1,
     'participant_location': (1, 0),
     'participant_payoff': -3.5,
     'strategy': 2,
     'supervisor_number': 2,
     'supervisor_payoff': 4,
     'supervisor_state': 0},
 8: {'average_payoff_neighbours_strat1': 0,
     'average_payoff_neighbours_strat2': -2.25,
     'average_payoff_neighbours_strat3': -8.0,
     'match_id': [(1, 0)],
     'match_strategy': 2,
     'new_strategy': 3,
     'participant_location': (1, 1),
     'participant_payoff': -2,
     'strategy': 3,
     'supervisor_number': 2,
     'supervisor_payoff': 4,
     'supervisor_state': 0},
 9: {'average_payoff_neighbours_strat1': -4.833333333333333,
     'average_payoff_neighbours_strat2': -1.0,
     'average_payoff_neighbours_strat3': -2.0,
     'match_id': [(0, 1)],
     'match_strategy': 2,
     'new_strategy': 3,
     'participant_location': (0, 0),
     'participant_payoff': -4,
     'strategy': 1,
     'supervisor_number': 3,
     'supervisor_payoff': 4,
     'supervisor_state': 1},
 10: {'average_payoff_neighbours_strat1': -4.5,
      'average_payoff_neighbours_strat2': -3.5,
      'average_payoff_neighbours_strat3': -5.0,
      'match_id': [(0, 0)],
      'match_strategy': 1,
      'new_strategy': 2,
      'participant_location': (0, 1),
      'participant_payoff': -1,
      'strategy': 2,
      'supervisor_number': 3,
      'supervisor_payoff': 4,
      'supervisor_state': 1},
 11: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': -1.8333333333333333,
      'average_payoff_neighbours_strat3': -4.0,
      'match_id': [(1, 1)],
      'match_strategy': 3,
      'new_strategy': 3,
      'participant_location': (1, 0),
      'participant_payoff': -8,
      'strategy': 3,
      'supervisor_number': 3,
      'supervisor_payoff': 16,
      'supervisor_state': 1},
 12: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': -2.25,
      'average_payoff_neighbours_strat3': -5.0,
      'match_id': [(1, 0)],
      'match_strategy': 3,
      'new_strategy': 3,
      'participant_location': (1, 1),
      'participant_payoff': -8,
      'strategy': 3,
      'supervisor_number': 3,
      'supervisor_payoff': 16,
      'supervisor_state': 1},
 13: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': -1.0,
      'average_payoff_neighbours_strat3': 0,
      'match_id': [(0, 1)],
      'match_strategy': 1,
      'new_strategy': 2,
      'participant_location': (0, 0),
      'participant_payoff': -4,
      'strategy': 1,
      'supervisor_number': 4,
      'supervisor_payoff': 4,
      'supervisor_state': 0},
 14: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': -1.0,
      'average_payoff_neighbours_strat3': -8.0,
      'match_id': [(0, 0)],
      'match_strategy': 1,
      'new_strategy': 1,
      'participant_location': (0, 1),
      'participant_payoff': -4,
      'strategy': 1,
      'supervisor_number': 4,
      'supervisor_payoff': 4,
      'supervisor_state': 0},
 15: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': -1.0,
      'average_payoff_neighbours_strat3': -8.0,
      'match_id': [(1, 1)],
      'match_strategy': 2,
      'new_strategy': 1,
      'participant_location': (1, 0),
      'participant_payoff': -4,
      'strategy': 1,
      'supervisor_number': 4,
      'supervisor_payoff': 4,
      'supervisor_state': 0},
 16: {'average_payoff_neighbours_strat1': -4.0,
      'average_payoff_neighbours_strat2': 0,
      'average_payoff_neighbours_strat3': -8.0,
      'match_id': [(1, 0)],
      'match_strategy': 1,
      'new_strategy': 2,
      'participant_location': (1, 1),
      'participant_payoff': -1,
      'strategy': 2,
      'supervisor_number': 4,
      'supervisor_payoff': 4,
      'supervisor_state': 0}}

# loop trough data, loop trough result_1, if supervisor number in data is the same as the key value in result1, update the average_payoff_neighbours_strat3 in data
# with the value of new strategy in result_1
import pprint
for key in data:
    supervisor_number = data[key]['supervisor_number']
    if supervisor_number in result_1:
        new_strategy = result_1[supervisor_number]['new_strategy']
        data[key]['average_payoff_neighbours_strat3'] = new_strategy

pprint.pprint(data)